name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
        env:
          RUST_BACKTRACE: 1
  
  check-no-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --no-default-features
        env:
          RUST_BACKTRACE: 1
  
  check-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo check --all-features
        env:
          RUST_BACKTRACE: 1
  
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt -- --check
  
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: "--default-theme ayu"
      - run: tar cf - target/doc/ | zstd -3 >rustdoc.tar.zst
      - uses: actions/upload-artifact@v2
        with:
          name: rustdoc
          path: rustdoc.tar.zst
  
  pages:
    runs-on: ubuntu-latest
    needs: [doc]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2
        with:
          name: rustdoc
      - name: Extract rustdoc
        run: |
          test ! -d ./doc || rm -r ./doc
          cat rustdoc.tar.zst | zstd -d | tar xf - --strip-components=1
          rm rustdoc.tar.zst
      - run: git status
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Pages for ${{github.sha}}"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
  